{
  "sksl": {
    "entrypoint": "bloom_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec4 FLT_flutter_local_extractBrightColor(vec4 color)\n{\n    float luma = dot(color.xyz, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));\n    float val = smoothstep(0.300000011920928955078125, 0.5, luma);\n    return color * val;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec4 sourceColor = uTexture.eval(uTexture_size * ( uv));\n    vec4 param = sourceColor;\n    vec4 bloomColor = FLT_flutter_local_extractBrightColor(param);\n    vec4 finalColor = sourceColor + (bloomColor * 0.25);\n    fragColor = vec4(finalColor.xyz, sourceColor.w);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}